# Generated by Django 4.2.30 on 2026-04-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_quiz_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='image',
        ),
    ]
