# Generated by Django 4.2.30 on 2026-04-30 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_option_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['name', '-created_at']},
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.TextField(default='option'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 30, 10, 31, 49, 800510)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='num_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
