# Generated by Django 4.2.30 on 2026-04-30 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_quiz_options_alter_option_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 30, 10, 33, 40, 481943, tzinfo=datetime.timezone.utc)),
        ),
    ]
