# Generated by Django 4.2.30 on 2026-04-30 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_quiz_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 30, 10, 36, 14, 19580, tzinfo=datetime.timezone.utc)),
        ),
    ]
