# Generated by Django 4.2.30 on 2026-04-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_quiz_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(default='desc'),
            preserve_default=False,
        ),
    ]
